//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSS_TicketsAttachedFiles
    {
        public long FilesID { get; set; }
        public Nullable<long> Files_TicketsID { get; set; }
        public Nullable<long> ActionID { get; set; }
        public string FilesName { get; set; }
        public string FilesTypes { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<long> CreatedByID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<long> UpdatedByID { get; set; }
        public int UpdatedCounts { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<long> DeletedByID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
