//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSS_Clients
    {
        public long ClientsID { get; set; }
        public string ShortName { get; set; }
        public string ClientsName { get; set; }
        public long Clients_ClassID { get; set; }
        public long Clients_CategoryID { get; set; }
        public Nullable<System.DateTime> ClientsContractEndDate { get; set; }
        public Nullable<long> DefaultDeveloper_ID { get; set; }
        public string contactperson { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string SMSMobile { get; set; }
        public string TeamViewerID { get; set; }
        public string TeamViewerPasswordHint { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<long> CreatedByID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<long> UpdatedByID { get; set; }
        public Nullable<int> UpdatedCounts { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<long> DeletedByID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> UserID { get; set; }
        public string ProductVersion { get; set; }
    
        public virtual CRM_LookupsCustomersCategories CRM_LookupsCustomersCategories { get; set; }
        public virtual CRM_LookupsCustomersClasses CRM_LookupsCustomersClasses { get; set; }
        public virtual CRM_Users CRM_Users { get; set; }
    }
}
