//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSS_TicketsActions
    {
        public long ActionID { get; set; }
        public Nullable<long> TicketID { get; set; }
        public string msg { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<bool> IsSeen { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
