//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSS_Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSS_Tickets()
        {
            this.TSS_TicketsAttachedFiles = new HashSet<TSS_TicketsAttachedFiles>();
            this.TSS_TicketsActions = new HashSet<TSS_TicketsActions>();
        }
    
        public long TicketsID { get; set; }
        public string TicketsSubject { get; set; }
        public System.DateTime TicketsCreatedTime { get; set; }
        public long Tickets_TypeID { get; set; }
        public long Tickets_StatusID { get; set; }
        public long Tickets_Client_ID { get; set; }
        public Nullable<long> Tickets_Mod_ID { get; set; }
        public Nullable<long> Tickets_Smod_ID { get; set; }
        public long Tickets_Priority_ID { get; set; }
        public Nullable<long> Tickets_DeveloperID { get; set; }
        public string TicketsAction { get; set; }
        public string TicketsSummery { get; set; }
        public string TicketsDesc { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<System.DateTime> ClosedTime { get; set; }
        public Nullable<bool> IsSolved { get; set; }
        public Nullable<System.DateTime> SolvedTime { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> TakenFromClientUserID { get; set; }
        public string TakenFromClientUserFullName { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<long> CreatedByID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<long> UpdatedByID { get; set; }
        public Nullable<int> UpdatedCounts { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<long> DeletedByID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual CRM_LookupsPriorities CRM_LookupsPriorities { get; set; }
        public virtual CRM_LookupsTicketsStatuses CRM_LookupsTicketsStatuses { get; set; }
        public virtual CRM_LookupsTicketsTypes CRM_LookupsTicketsTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSS_TicketsAttachedFiles> TSS_TicketsAttachedFiles { get; set; }
        public virtual Module Module { get; set; }
        public virtual TSS_Clients TSS_Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSS_TicketsActions> TSS_TicketsActions { get; set; }
    }
}
